const mongoose=require('mongoose')
const Schema=mongoose.Schema
const fighterSchema=new Schema({
    name:{
        type:String,
        required:true
    },
    nickname:{
        type:String
    },
    dob:{
        type:Date
    },
    nationality:{
        type:String,
        required:true
    },
    weightClass:{
        type:String,
        required:true
    },
    height:{
        type:Number,
    },
    reach:{
        type:Number,
    },
    stance:{
        type:String,
        enum:['Orthodox','Southpaw']
    },
    wins:{
        type:Number,
        default:0
    },
    losses:{
        type:Number,
        default:0
    },
    draws:{
        type:Number,
        default:0
    },
    imageUrl:{
        type:String
    },
    status:{
        type:String,
        enum:['Active','Retired','Inactive'],
        default:'Active'
    },
    socialMediaLinks:{
        instagram:String,
        facebook:String,
        twitter:String
    },
    imageUrl:{
        type:String
    },
    imagePublicId:{
        type:String
    },
    gym:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Gym'
    }
},{
    timestamps:true
})
module.exports=mongoose.model('Fighter',fighterSchema)